# **Assignment 1: Demand prediction of bike sharing system**

Bike sharing services are nowadays spread all over the world. They are beneficial for cities as they offer a climate neutral and healthy way of transportation. Moreover, similar to e-scooters, for the companies and transportation researchers they generate valuable data. This includes the trip route, trip origins and destinations, duration, and much more.

In this assignment we use a public bike sharing dataset from Washington, D.C., USA. published by Fanaee-T, H. (2013). Bike Sharing [Dataset]. UCI Machine Learning Repository. https://doi.org/10.24432/C5W894.

## Your Task

Your task in this assignment is:

1) to predict the demand of hourly rentals (**target-column: cnt**) using the [XGBoost](https://xgboost.readthedocs.io/en/stable/) and linear regression model. In this notebook we have provided you with the basic structure how to approach the problem. Feel free to reuse and improve parts of the exercise material.

2) After you have created the model please upload your code to Github and post the link to the notebook in the corresponding forum for the assignment with a short text describing how you have solved the task.

## Load data

You can also find more information about the data and the columns at: https://archive.ics.uci.edu/dataset/275/bike+sharing+dataset

In [114]:
import pandas as pd

url = 'https://raw.githubusercontent.com/zhenliangma/Applied-AI-in-Transportation/master/Exercise_2_regression_model/Exercise2BikeSharing.csv'
df = pd.read_csv(url)

#df = pd.read_csv('Exercise2BikeSharing.csv')
df.head(10)

,instant,dteday,season,yr,mnth,hr,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
0,1,2011-01-01,1,0,1,0,0,6,0,1,0.24,0.2879,0.81,0.0000,3,13,16
1,2,2011-01-01,1,0,1,1,0,6,0,1,0.22,0.2727,0.80,0.0000,8,32,40
2,3,2011-01-01,1,0,1,2,0,6,0,1,0.22,0.2727,0.80,0.0000,5,27,32
3,4,2011-01-01,1,0,1,3,0,6,0,1,0.24,0.2879,0.75,0.0000,3,10,13
4,5,2011-01-01,1,0,1,4,0,6,0,1,0.24,0.2879,0.75,0.0000,0,1,1
5,6,2011-01-01,1,0,1,5,0,6,0,2,0.24,0.2576,0.75,0.0896,0,1,1
6,7,2011-01-01,1,0,1,6,0,6,0,1,0.22,0.2727,0.80,0.0000,2,0,2
7,8,2011-01-01,1,0,1,7,0,6,0,1,0.20,0.2576,0.86,0.0000,1,2,3
8,9,2011-01-01,1,0,1,8,0,6,0,1,0.24,0.2879,0.75,0.0000,1,7,8
9,10,2011-01-01,1,0,1,9,0,6,0,1,0.32,0.3485,0.76,0.0000,8,6,14

In [115]:
df.shape

(17379, 17)

In [116]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17379 entries, 0 to 17378
Data columns (total 17 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   instant     17379 non-null  int64
 1   dteday      17379 non-null  object
 2   season      17379 non-null  int64
 3   yr          17379 non-null  int64
 4   mnth        17379 non-null  int64
 5   hr          17379 non-null  int64
 6   holiday     17379 non-null  int64
 7   weekday     17379 non-null  int64
 8   workingday  17379 non-null  int64
 9   weathersit  17379 non-null  int64
 10  temp        17379 non-null  float64
 11  atemp       17379 non-null  float64
 12  hum         17379 non-null  float64
 13  windspeed   17379 non-null  float64
 14  casual      17379 non-null  int64
 15  registered  17379 non-null  int64
 16  cnt         17379 non-null  int64
dtypes: float64(4), int64(12), object(1)
memory usage: 2.3+ MB

In [118]:
df.drop(columns=['dteday'], inplace=True)
corr_matrix = df.corr()
corr_matrix['cnt'].sort_values(ascending=False)

cnt           1.000000
registered    0.972151
casual        0.694564
temp          0.404772
atemp         0.400929
hr            0.394071
instant       0.278379
yr            0.250495
season        0.178056
mnth          0.120638
windspeed     0.093234
workingday    0.030284
weekday       0.026900
holiday      -0.030927
weathersit   -0.142426
hum          -0.322911
Name: cnt, dtype: float64

## Train / Test split
- Target: `cnt` (count of total rental bikes including both casual and registered)
- Predictors: weather (`temp`, `atemp`, `hum`, `windspeed`, `weathersit`), calendar (`hr`, `weekday`, `workingday`, `holiday`, `season`), and `yr`.
- We keep it simple; you can expand features (e.g., interactions) later.

In [119]:
from sklearn.model_selection import train_test_split
target = 'cnt'

X = df.copy()
y = df[target].astype(float)

X.drop(columns=[target], inplace=True)

X.drop(columns=['atemp', 'casual', 'registered', 'instant'], inplace=True)

# Train/test split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

## Data Processing / Feature Engineering

Before training the model think about data processing and feature engineering steps if applicable, such as:
- adding/removal of features
- normalization
- one hot encoding
- ...

Normalizing

In [120]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

## Hyperparameter optimization
Hyperparameter tuning helps find the best set of hyperparameters for your model. Use Grid Search or Random Search with Cross Validation from scikit-learn to search for the best combination of parameters.

In [121]:
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVR

# Define a parameter grid for hyperparameter tuning
param_grid = {
    'kernel': ['linear', 'rbf'],
    'C': [ 1, 10],
    'epsilon': [ 1, 10]
}

# Create the GridSearchCV object
grid_search = GridSearchCV(SVR(), param_grid, cv=5, verbose=2)

# Fit the grid search to the scaled training data
grid_search.fit(X_train_scaled, y_train)

# Get the best parameters
best_params = grid_search.best_params_

print("Best Parameters:", best_params)
print("Best Score:", grid_search.best_score_)

Fitting 5 folds for each of 8 candidates, totalling 40 fits
[CV] END ......................C=1, epsilon=1, kernel=linear; total time=   7.3s
[CV] END ......................C=1, epsilon=1, kernel=linear; total time=   7.5s
[CV] END ......................C=1, epsilon=1, kernel=linear; total time=   6.4s
[CV] END ......................C=1, epsilon=1, kernel=linear; total time=   7.6s
[CV] END ......................C=1, epsilon=1, kernel=linear; total time=   6.4s
[CV] END .........................C=1, epsilon=1, kernel=rbf; total time=   9.5s
[CV] END .........................C=1, epsilon=1, kernel=rbf; total time=   9.6s
[CV] END .........................C=1, epsilon=1, kernel=rbf; total time=   8.2s
[CV] END .........................C=1, epsilon=1, kernel=rbf; total time=   9.5s
[CV] END .........................C=1, epsilon=1, kernel=rbf; total time=   9.5s
[CV] END .....................C=1, epsilon=10, kernel=linear; total time=   5.9s
[CV] END .....................C=1, epsilon=10, kernel=linear; total time=   7.2s
[CV] END .....................C=1, epsilon=10, kernel=linear; total time=   6.0s
[CV] END .....................C=1, epsilon=10, kernel=linear; total time=   7.1s
[CV] END .....................C=1, epsilon=10, kernel=linear; total time=   5.9s
[CV] END ........................C=1, epsilon=10, kernel=rbf; total time=   8.8s
[CV] END ........................C=1, epsilon=10, kernel=rbf; total time=   8.7s
[CV] END ........................C=1, epsilon=10, kernel=rbf; total time=   8.1s
[CV] END ........................C=1, epsilon=10, kernel=rbf; total time=   8.8s
[CV] END ........................C=1, epsilon=10, kernel=rbf; total time=   8.2s
[CV] END .....................C=10, epsilon=1, kernel=linear; total time=   7.8s
[CV] END .....................C=10, epsilon=1, kernel=linear; total time=   8.2s
[CV] END .....................C=10, epsilon=1, kernel=linear; total time=   7.1s
[CV] END .....................C=10, epsilon=1, kernel=linear; total time=   8.2s
[CV] END .....................C=10, epsilon=1, kernel=linear; total time=   7.4s
[CV] END ........................C=10, epsilon=1, kernel=rbf; total time=   9.2s
[CV] END ........................C=10, epsilon=1, kernel=rbf; total time=   9.5s
[CV] END ........................C=10, epsilon=1, kernel=rbf; total time=   9.6s
[CV] END ........................C=10, epsilon=1, kernel=rbf; total time=   8.3s
[CV] END ........................C=10, epsilon=1, kernel=rbf; total time=   9.5s
[CV] END ....................C=10, epsilon=10, kernel=linear; total time=   7.7s
[CV] END ....................C=10, epsilon=10, kernel=linear; total time=   6.8s
[CV] END ....................C=10, epsilon=10, kernel=linear; total time=   8.0s
[CV] END ....................C=10, epsilon=10, kernel=linear; total time=   6.9s
[CV] END ....................C=10, epsilon=10, kernel=linear; total time=   8.0s
[CV] END .......................C=10, epsilon=10, kernel=rbf; total time=   8.2s
[CV] END .......................C=10, epsilon=10, kernel=rbf; total time=   8.3s
[CV] END .......................C=10, epsilon=10, kernel=rbf; total time=   9.0s
[CV] END .......................C=10, epsilon=10, kernel=rbf; total time=   7.8s
[CV] END .......................C=10, epsilon=10, kernel=rbf; total time=   8.6s
Best Parameters: {'C': 10, 'epsilon': 10, 'kernel': 'rbf'}
Best Score: 0.5125658834406476

In [126]:
# Create an SVR model with the best parameters from the grid search
best_svr = SVR(kernel=best_params['kernel'], C=best_params['C'], epsilon=best_params['epsilon'])
best_svr.fit(X_train, y_train)

SVR(C=10, epsilon=10)

In [128]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

y_pred = best_svr.predict(X_test)
mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)
print(f"Mean Absolute Error: {mae}")
print(f"Mean Squared Error: {mse}")
print(f"R-squared: {r2}")

Mean Absolute Error: 78.03116516396986
Mean Squared Error: 15918.404691369342
R-squared: 0.49729360777188725

## Train the XGBoost and Linear regression models
Now, create an XGBoost and linear regression model using the best parameters and train them using the training data.

In [123]:
# Your code here

## Make predictions
Use the trained models to make predictions on the test data and compare the performance of the XGBoost and linear regression models using metrics like Mean Squared Error (MSE) and R-squared.

In [124]:
# Your code here

## Visualize the predictions and compare the mdoels
Create a "Actual vs. Predicted Values" graph to give a visual inspection of the prediction quality.

In [125]:
# Your Code here